apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
stringData:
  operator-credentials.json: |-
    {
      "secretKey": "${OP_SECRET_KEY}",
      "masterPassword": "${OP_MASTER_PASSWORD}"
    }
