apiVersion: v1
kind: Secret
metadata:
  name: credentials-asm
  labels:
    type: asm 
type: Opaque
stringData:
  operator-credentials.json: |-
    {
      "accessKeyID": "",
      "secretAccessKey": "",
      "sessionToken": ""
    }
