apiVersion: v1
kind: Secret
metadata:
  name: credentials-akv
  labels:
    type: akv
type: Opaque
stringData:
  credentials.json: |-
    {
      "clientId": "",
      "clientSecret": "",
      "tenantId": "",
      "akvName": ""
    }
