apiVersion: v1
kind: Secret
metadata:
  name: credentials-onepassword
  labels:
    type: onepassword
type: Opaque
stringData:
  credentials.json: |-
    {
      "secretKey": "${OP_SECRET_KEY}",
      "masterPassword": "${OP_MASTER_PASSWORD}"
    }
