apiVersion: v1
kind: Secret
metadata:
  name: operator-config
type: Opaque
stringData:
  operator-config.json: |-
    {
      "Type": "dummy",
      "Parameters": {
        "Suffix": "-dummyexample"
      }
    }
