apiVersion: v1
kind: Secret
metadata:
  name: externalsecret-operator-config
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  operator-config.json: |-
    {
      "Type": "onepassword",
      "Parameters": {
        "domain": "${OP_DOMAIN}",
        "email": "${OP_EMAIL}",
        "secretKey": "${OP_SECRET_KEY}",
        "masterPassword": "${OP_MASTER_PASSWORD}",
        "vault": "${OP_VAULT}"
      }
    }
