# permissions for end users to edit externalsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalsecret-editor-role
rules:
- apiGroups:
  - secrets.externalsecret-operator.container-solutions.com
  resources:
  - externalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.externalsecret-operator.container-solutions.com
  resources:
  - externalsecrets/status
  verbs:
  - get
