# permissions for end users to view secretstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretstore-viewer-role
rules:
- apiGroups:
  - store.externalsecret-operator.container-solutions.com
  resources:
  - secretstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - store.externalsecret-operator.container-solutions.com
  resources:
  - secretstores/status
  verbs:
  - get
