apiVersion: secrets.externalsecret-operator.container-solutions.com/v1alpha1
kind: ExternalSecret
metadata:
  name: externalsecret-sample
spec:
  storeRef: 
    name: externalsecret-operator-secretstore-sample
    namespace: externalsecret-operator-system
  data:
    - key: backend-secret-text
      version: latest
    - key: backend-secret-file
      version: latest