apiVersion: store.externalsecret-operator.container-solutions.com/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  controller: staging
  # Sample store types
  #
  # Dummy  
  store:
    type: dummy
    auth: 
      secretRef: 
        name: externalsecret-operator-credentials-dummy
        namespace: externalsecret-operator-system
    parameters:
      Suffix: TestParam
      Test: TestParam

  # AWS Secrets Manager
  # store:
  #   type: asm
  #   auth: 
  #     secretRef: 
  #       name: externalsecret-operator-credentials-asm
  #       namespace: externalsecret-operator-system
  #   parameters:
  #     region: eu-west-2
  
  # GCP Secret Manager
  # store:
  #   type: gsm
  #   auth: 
  #     secretRef: 
  #       name: externalsecret-operator-credentials-gsm
  #       namespace: externalsecret-operator-system
  #   parameters:
  #     projectID: external-secrets-operator

  # Onepassword
  # store:
  #   type: onepassword
  #   auth: 
  #     secretRef: 
  #       name: externalsecret-operator-credentials-onepassword
  #       namespace: externalsecret-operator-system
  #   parameters:
  #     vault: Personal
  #     email: email@email-provider.com
  #     domain: domain.onepassword.com
