apiVersion: store.externalsecret-operator.container-solutions.com/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  controller: staging
  # Sample store types
  #
  # Dummy  
  store:
    type: dummy
    auth:
      secretRef:
        name: externalsecret-operator-credentials-dummy
    parameters:
      Suffix: TestParam
      Test: TestParam

  # AWS Secrets Manager
  # store:
  #   type: asm
  #   auth: 
  #     secretRef: 
  #       name: externalsecret-operator-credentials-asm
  #   parameters:
  #     region: eu-west-2
  
  # GCP Secret Manager
  # store:
  #   type: gsm
  #   auth: 
  #     secretRef: 
  #       name: externalsecret-operator-credentials-gsm
  #   parameters:
  #     projectID: external-secrets-operator

  # Gitlab Project Variables
  # store:
  #   type: gitlab
  #   auth:
  #     secretRef:
  #       name: externalsecret-operator-credentials-gitlab
  #   parameters:
  #     baseURL: https://gitlab.com
  #     projectID: 12345678

  #Azure Key Vault
  # store:
  #   type: akv
  #   auth:
  #     secretRef:
  #       name: externalsecret-operator-credentials-akv
  #   parameters: {}
