apiVersion: store.externalsecret-operator.container-solutions.com/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  controller: staging
  store:
    type: dummy
    auth: 
      secretRef: 
        name: externalsecret-operator-config
        namespace: externalsecret-operator-system
    parameters:
      Suffix: I am definitely a parameter

  # store:
  #   type: asm
  #   auth: 
  #     secretRef: 
  #       name: externalsecret-operator-config
  #       namespace: externalsecret-operator-system
  #   parameters:
  #     sts: false
  #     region: eu-west-2

  # store:
  #   type: gsm
  #   auth: 
  #     secretRef: 
  #       name: externalsecret-operator-config
  #       namespace: externalsecret-operator-system
  #   parameters:
  #     projectID: external-secrets-operator

  # store:
  #   type: onepassword
  #   auth: 
  #     secretRef: 
  #       name: externalsecret-operator-config
  #       namespace: externalsecret-operator-system
  #   parameters:
  #     vault: Personal
  #     email: 
  #     domain: 

