apiVersion: v1
kind: Secret
metadata:
  name: config
type: Opaque
stringData:
  operator-config.json: |-
    {
      "secretKey": "${OP_SECRET_KEY}",
      "masterPassword": "${OP_MASTER_PASSWORD}",
    }
