{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "externalsecret-operator.name" . }}
    helm.sh/chart: {{ include "externalsecret-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "externalsecret-operator.fullname" . }}-watch
  namespace: {{ template "externalsecret-operator.watchNamespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "externalsecret-operator.fullname" . }}-watch
subjects:
  - kind: ServiceAccount
    name: {{ template "externalsecret-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
