{{- if and .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "externalsecret-operator.fullname" . }}-run
  labels:
    app.kubernetes.io/name: {{ include "externalsecret-operator.name" . }}
    helm.sh/chart: {{ include "externalsecret-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
rules:

  # Allow the External Secret Operator to get/list/watch common resources
- apiGroups:
  - ""
  resources:
  - pods
  - endpoints
  - persistentvolumeclaims
  - events
  - secrets
  - namespaces
  verbs:
  - get
  - list
  - watch

  # Allow the External Secret Operator to create/delete services resources
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - "*"

  # Allow the External Secret Operator to handle ConfigMaps
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"

  # Allow the External Secret Operator to get/list/watch apps related resources
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
  - list
  - watch
{{- end -}}
