apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ include "externalsecret-operator.name" . }}
    helm.sh/chart: {{ include "externalsecret-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ template "externalsecret-operator.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.secret.key }}: |-
{{ toPrettyJson .Values.secret.data | indent 4 }}
  
