{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "externalsecret-operator.name" . }}
    helm.sh/chart: {{ include "externalsecret-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ template "externalsecret-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}