apiVersion: v1
appVersion: "1.0"
description: A Chart for the External Secret Operator
keywords:
  - aws
  - secrets
  - 1password
  - security
  - automation
home: https://github.com/ContainerSolutions/externalsecret-operator
name: externalsecret-operator
maintainers:
  - name: riccardomc
version: 0.1.0
